# --- !Ups

CREATE TABLE IF NOT EXISTS USER(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRICE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS CART(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USER_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL
);

# --- !Downs

DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USER;
